# MongoDB Atlas Cloud Database Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://myAtlasDBUser:doAhRtrOrMztWcXT@developmentclustrer.w06y2m1.mongodb.net/portfolio_db?appName=DevelopmentClustrer}

# Exclude JPA / Hibernate auto-configuration under MongoDB profile to prevent repository bean conflicts
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
